# Generated by Django 5.1.4 on 2024-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_likes',
            field=models.TextField(blank=True),
        ),
    ]
