# Generated by Django 4.2.16 on 2025-01-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_likes',
            field=models.IntegerField(default=0),
        ),
    ]
