# Generated by Django 5.1.4 on 2024-12-09 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('image_url', models.CharField(max_length=512)),
                ('likes', models.ManyToManyField(related_name='liked_places', through='places.Like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('account', 'place')},
        ),
    ]
