# Generated by Django 5.1.4 on 2024-12-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_latitude_remove_place_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='time',
            field=models.CharField(default='별도 운영시간 없음', max_length=200),
        ),
    ]
