name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  django-format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker
        run: docker compose -f github-actions.docker-compose.yml build

      - name: Create env file
        env:
          DJANGO_TEST_ENV: ${{ secrets.DJANGO_TEST_ENV }}
        run: |
          touch .env.django
          echo "$DJANGO_TEST_ENV" >> .env.django

      - name: Run isort
        run: docker compose -f github-actions.docker-compose.yml run django isort back/ --check

      - name: Run black
        run: docker compose -f github-actions.docker-compose.yml run django black back/ --check

      - name: Run flake8
        run: docker compose -f github-actions.docker-compose.yml run django flake8

      - name: Run mypy
        run: docker compose -f github-actions.docker-compose.yml run django mypy --config mypy.ini back/


  django-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file
        env:
          DJANGO_TEST_ENV: ${{ secrets.DJANGO_TEST_ENV }}
        run: |
          touch .env.django
          echo "$DJANGO_TEST_ENV" >> .env.django

      - name: Build docker
        run: docker compose -f github-actions.docker-compose.yml build
      #sh
      - name: Run tests
        run: docker compose -f github-actions.docker-compose.yml run django sh -c "coverage run manage.py test back && coverage report --fail-under=90"
